### ISSUE TITLE
EqCard Error

### ISSUE THREAD

**Issue by edeuss** [kekland/equinox#1]
Here is what I am getting:

``` 
flutter: ══╡ EXCEPTION CAUGHT BY WIDGETS LIBRARY ╞═══════════════════════════════════════════════════════════
flutter: The following NoSuchMethodError was thrown building EqCard(dirty):
flutter: The getter 'theme' was called on null.
flutter: Receiver: null
flutter: Tried calling: theme
flutter:
flutter: When the exception was thrown, this was the stack:
flutter: #0      Object.noSuchMethod (dart:core-patch/object_patch.dart:50:5)
flutter: #1      EqTheme.of (package:equinox/components/global/theming.dart:14:27)
flutter: #2      EqCard.build (package:equinox/components/card/card.dart:87:25)
flutter: #3      StatelessElement.build (package:flutter/src/widgets/framework.dart:3974:28)
flutter: #4      ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3924:15)
flutter: #5      Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #6      ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
flutter: #7      ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #8      Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #9      MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5198:32)
flutter: #10     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #11     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #12     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
flutter: #13     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #14     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #15     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
flutter: #16     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #17     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #18     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #19     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #20     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
flutter: #21     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #22     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #23     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #24     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
flutter: #25     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #26     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #27     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
flutter: #28     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #29     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #30     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
flutter: #31     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #32     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #33     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
flutter: #34     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #35     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #36     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
flutter: #37     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #38     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #39     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #40     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #41     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
flutter: #42     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
flutter: #43     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #44     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #45     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #46     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
flutter: #47     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #48     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #49     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #50     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #51     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
flutter: #52     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #53     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #54     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #55     SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
flutter: #56     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #57     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #58     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #59     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #60     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
flutter: #61     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
flutter: #62     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #63     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #64     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #65     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #66     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #67     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
flutter: #68     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #69     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #70     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #71     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #72     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #73     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
flutter: #74     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #75     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #76     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #77     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #78     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #79     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
flutter: #80     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #81     ParentDataElement.mount (package:flutter/src/widgets/framework.dart:4279:11)
flutter: #82     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #83     MultiChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5198:32)
flutter: #84     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #85     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #86     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #87     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #88     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
flutter: #89     StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
flutter: #90     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #91     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #92     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #93     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #94     Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #95     ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
flutter: #96     ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #97     Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #98     Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #99     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #100    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #101    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
flutter: #102    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
flutter: #103    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #104    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #105    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #106    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
flutter: #107    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #108    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #109    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #110    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #111    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
flutter: #112    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #113    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #114    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #115    SingleChildRenderObjectElement.mount (package:flutter/src/widgets/framework.dart:5092:14)
flutter: #116    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #117    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #118    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #119    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #120    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
flutter: #121    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
flutter: #122    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #123    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #124    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #125    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #126    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #127    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
flutter: #128    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
flutter: #129    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #130    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #131    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #132    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #133    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #134    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
flutter: #135    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #136    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #137    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #138    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #139    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #140    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
flutter: #141    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #142    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #143    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #144    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #145    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #146    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
flutter: #147    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
flutter: #148    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #149    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #150    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #151    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #152    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #153    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
flutter: #154    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
flutter: #155    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #156    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #157    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #158    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #159    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #160    ComponentElement._firstBuild (package:flutter/src/widgets/framework.dart:3907:5)
flutter: #161    StatefulElement._firstBuild (package:flutter/src/widgets/framework.dart:4053:11)
flutter: #162    ComponentElement.mount (package:flutter/src/widgets/framework.dart:3902:5)
flutter: #163    Element.inflateWidget (package:flutter/src/widgets/framework.dart:3084:14)
flutter: #164    Element.updateChild (package:flutter/src/widgets/framework.dart:2887:12)
flutter: #165    ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:3935:16)
flutter: #166    Element.rebuild (package:flutter/src/widgets/framework.dart:3721:5)
flutter: #167    BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2340:33)
flutter: #168    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding&WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:700:20)
flutter: #169    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding&PaintingBinding&SemanticsBinding&RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:285:5)
flutter: #170    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1016:15)
flutter: #171    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:958:9)
flutter: #172    _WidgetsFlutterBinding&BindingBase&GestureBinding&ServicesBinding&SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:874:5)
flutter: #176    _invoke (dart:ui/hooks.dart:236:10)
flutter: #177    _drawFrame (dart:ui/hooks.dart:194:3)
flutter: (elided 3 frames from package dart:async)
flutter: ════════════════════════════════════════════════════════════════════════════════════════════════════

```

**Comment by edeuss** [comment]
I think it has something to do with this. I don't see what it being put into the EqThemeData. 

<img width="340" alt="Screen Shot 2019-07-05 at 3 09 29 PM" src="https://user-images.githubusercontent.com/13773566/60746965-efb24980-9f36-11e9-93d1-5a72a4966a31.png">

**Comment by kekland** [comment]
When using the card, there must be a parent EqLayout or EquinoxApp widget with field `theme` set. I'll add this to documentation soon.

**Comment by kekland** [comment]
I guess I can close it now.
